export const staticProductCatalog = [
    { id: "static-home-1", name: "Terracotta Vase", price: 999, image: "/images/vase.jpg", category: "home-decor" },
    { id: "static-home-2", name: "Hand-painted Wall Plate", price: 1299, image: "/images/platesss.jpg", category: "home-decor" },
    { id: "static-home-3", name: "Wooden Sculpture", price: 1599, image: "/images/wooden.jpg", category: "home-decor" },
    { id: "static-home-4", name: "Aromatic Candle", price: 499, image: "/images/candle.jpg", category: "home-decor" },

    { id: "static-fashion-1", name: "Elegant Saree", price: 1299, image: "/images/saree.jpg", category: "fashion" },
    { id: "static-fashion-2", name: "Cotton Kurta", price: 1379, image: "/images/cloth.jpg", category: "fashion" },
    { id: "static-fashion-3", name: "Khadi Set", price: 1459, image: "/images/khadi.jpg", category: "fashion" },
    { id: "static-fashion-4", name: "Woolen Shawl", price: 1539, image: "/images/wool.jpg", category: "fashion" },
    { id: "static-fashion-5", name: "Designer Dupatta", price: 1619, image: "/images/duppata.jpg", category: "fashion" },
    { id: "static-fashion-6", name: "Fashion Top", price: 1699, image: "/images/fashion.jpg", category: "fashion" },
    { id: "static-fashion-7", name: "Handbag", price: 1779, image: "/images/purse.jpg", category: "fashion" },
    { id: "static-fashion-8", name: "Pearl Necklace", price: 1859, image: "/images/pearl.jpeg", category: "fashion" },

    { id: "static-gifts-1", name: "Handcrafted Wooden Frame", price: 1499, image: "/images/wood frame.jpg", category: "gifts" },
    { id: "static-gifts-2", name: "Resin Candle Holder", price: 999, image: "/images/resin candle holder.jpg", category: "gifts" },
    { id: "static-gifts-3", name: "Embroidered Gift Box", price: 1299, image: "/images/gift box.jpg", category: "gifts" },
    { id: "static-gifts-4", name: "Artisanal Paper Journal", price: 899, image: "/images/journal.jpg", category: "gifts" },

    { id: "static-jewel-1", name: "Jewelry 1", price: 799, image: "/images/j1.jpg", category: "jewelry" },
    { id: "static-jewel-2", name: "Jewelry 2", price: 869, image: "/images/j2.jpg", category: "jewelry" },
    { id: "static-jewel-3", name: "Jewelry 3", price: 939, image: "/images/j3.jpg", category: "jewelry" },
    { id: "static-jewel-4", name: "Jewelry 4", price: 1009, image: "/images/j4.jpg", category: "jewelry" },

    { id: "static-kd-1", name: "Editor's Pick 1", price: 699, image: "/images/d1.jpeg", category: "kitchen-dining" },
    { id: "static-kd-2", name: "Editor's Pick 2", price: 819, image: "/images/d2.jpeg", category: "kitchen-dining" },
    { id: "static-kd-3", name: "Editor's Pick 3", price: 939, image: "/images/d3.jpeg", category: "kitchen-dining" },
    { id: "static-kd-4", name: "Editor's Pick 4", price: 1059, image: "/images/d4.jpeg", category: "kitchen-dining" },
    { id: "static-kd-5", name: "Editor's Pick 5", price: 1179, image: "/images/d5.jpeg", category: "kitchen-dining" },
    { id: "static-kd-6", name: "Editor's Pick 6", price: 1299, image: "/images/d6.jpg", category: "kitchen-dining" },
    { id: "static-kd-7", name: "Editor's Pick 7", price: 1419, image: "/images/d7.jpg", category: "kitchen-dining" },
    { id: "static-kd-8", name: "Editor's Pick 8", price: 1539, image: "/images/d8.jpg", category: "kitchen-dining" },

    { id: "static-care-1", name: "Deal 1", price: 299, image: "/images/p3.jpg", category: "personal-care" },
    { id: "static-care-2", name: "Deal 2", price: 349, image: "/images/p2.jpg", category: "personal-care" },
    { id: "static-care-3", name: "Deal 3", price: 399, image: "/images/p1.jpg", category: "personal-care" },

    { id: "static-toy-1", name: "Popular Toy 1", price: 399, image: "/images/t1.jpeg", category: "toys" },
    { id: "static-toy-2", name: "Popular Toy 2", price: 469, image: "/images/t2.jpeg", category: "toys" },
    { id: "static-toy-3", name: "Popular Toy 3", price: 539, image: "/images/t3.jpeg", category: "toys" },
    { id: "static-toy-4", name: "Popular Toy 4", price: 609, image: "/images/t4.jpeg", category: "toys" },
    { id: "static-toy-5", name: "Popular Toy 5", price: 679, image: "/images/t5.jpeg", category: "toys" },
    { id: "static-toy-6", name: "Popular Toy 6", price: 749, image: "/images/t6.jpeg", category: "toys" },
    { id: "static-toy-7", name: "Popular Toy 7", price: 819, image: "/images/t7.jpeg", category: "toys" },
    { id: "static-toy-8", name: "Popular Toy 8", price: 889, image: "/images/t8.jpeg", category: "toys" },

    { id: "static-craft-1", name: "Blue Pottery Vase", price: 1299, image: "/images/crafts-1.jpg", category: "regional-crafts" },
    { id: "static-craft-2", name: "Bandhani Dupatta", price: 899, image: "/images/crafts-2.jpg", category: "regional-crafts" },
    { id: "static-craft-3", name: "Block Print Wall Hanging", price: 1599, image: "/images/crafts-3.jpg", category: "regional-crafts" },
    { id: "static-craft-4", name: "Rajasthani Art Plate", price: 749, image: "/images/crafts-4.jpg", category: "regional-crafts" },
    { id: "static-craft-5", name: "Kantha Cloth Purse", price: 599, image: "/images/crafts-5.jpg", category: "regional-crafts" },
    { id: "static-craft-6", name: "Terracotta Decorative Pot", price: 449, image: "/images/crafts-6.jpg", category: "regional-crafts" },
    { id: "static-craft-7", name: "Bengali Textile Art", price: 1199, image: "/images/crafts-7.jpg", category: "regional-crafts" },
    { id: "static-craft-8", name: "Handwoven Fabric", price: 999, image: "/images/crafts-8.jpg", category: "regional-crafts" },
    { id: "static-craft-9", name: "Mirror Work Potli", price: 699, image: "/images/crafts-9.jpg", category: "regional-crafts" },
    { id: "static-craft-10", name: "Bandhani Saree", price: 2499, image: "/images/crafts-10.jpg", category: "regional-crafts" },
    { id: "static-craft-11", name: "Traditional Potli Bag", price: 549, image: "/images/crafts-11.jpg", category: "regional-crafts" },
    { id: "static-craft-12", name: "Embroidered Potli", price: 649, image: "/images/crafts-12.jpg", category: "regional-crafts" },
];
